"""Backlog-aware Ray data dispatcher."""

from __future__ import annotations

from ray_dispatcher.adapter import NativeRayAdapter, RayAdapter
from ray_dispatcher.checkpoint import (
    CheckpointDocument,
    MemoryCheckpointStore,
    SQLiteCheckpointStore,
)
from ray_dispatcher.discovery import (
    WorkerDiscoveryError,
    discover_worker_roots,
    discover_workers,
)
from ray_dispatcher.dispatcher import KafkaRetentionGap, RayDispatcher, StaleBatchError
from ray_dispatcher.plugins import (
    PluginManager,
    PluginStore,
    ReloadResult,
    ValidationResult,
    create_plugin_router,
    validate_worker_py,
)
from ray_dispatcher.event_log import (
    EVENT_BATCH_COMMITTED,
    EVENT_BATCH_SKIPPED,
    EVENT_RUN_FAILED,
    EVENT_SNAPSHOT,
    EVENT_TRIGGER_EVALUATED,
    EVENT_WINDOW_OVER_CAPACITY,
    EventLog,
    EventLogError,
    create_event_log,
    default_event_log,
    discover_event_hooks,
    hook,
)
from ray_dispatcher.failures import MemoryFailureStore, SQLiteFailureStore
from ray_dispatcher.models import (
    BatchStatus,
    BatchWindow,
    DispatchRequest,
    ExecutionMode,
    ExecutionResult,
    FailureRecord,
    FailureRunDetail,
    HandlerRequest,
    HandlerSpec,
    KafkaSource,
    MultiSourceWindowState,
    PostgresCursor,
    PostgresSource,
    RunStatus,
    SourceKind,
    SourceSpec,
    SourceState,
    handler_shard_size,
    merge_batch_windows,
    normalize_batch_size,
)
from ray_dispatcher.policy import (
    BacklogPressure,
    ConditionResult,
    ConditionVerdict,
    Decision,
    DispatcherConfig,
    HasBacklog,
    HasCapacity,
    HasTimeWindow,
    SoftAction,
    SourceIdle,
    TargetReached,
    TriggerContext,
    TriggerDecision,
    TriggerPolicy,
)
from ray_dispatcher.readers import (
    CompositePayloadReader,
    KafkaPayloadReader,
    PayloadReader,
    PostgresPayloadReader,
    merge_fetch_results,
)
from ray_dispatcher.registries import (
    ResourceRegistry,
    ResourceSpec,
    SourceRegistry,
    build_resource_registry,
    build_source_registry,
    resolve_resource,
    resolve_source,
    resource_from_mapping,
    source_from_mapping,
)
from ray_dispatcher.resources import ResourceLoader
from ray_dispatcher.rules import EqRuleLabeler, build_eq_rule_labeler
from ray_dispatcher.sources import (
    EmptyPostgresSource,
    SourceDependencyError,
    SourceObserver,
)

__all__ = [
    "BacklogPressure",
    "BatchStatus",
    "BatchWindow",
    "CheckpointDocument",
    "CompositePayloadReader",
    "ConditionResult",
    "ConditionVerdict",
    "Decision",
    "DispatchRequest",
    "DispatcherConfig",
    "EVENT_BATCH_COMMITTED",
    "EVENT_BATCH_SKIPPED",
    "EVENT_RUN_FAILED",
    "EVENT_SNAPSHOT",
    "EVENT_TRIGGER_EVALUATED",
    "EVENT_WINDOW_OVER_CAPACITY",
    "EmptyPostgresSource",
    "EqRuleLabeler",
    "EventLog",
    "EventLogError",
    "ExecutionMode",
    "ExecutionResult",
    "FailureRecord",
    "FailureRunDetail",
    "HandlerRequest",
    "HandlerSpec",
    "HasBacklog",
    "HasCapacity",
    "HasTimeWindow",
    "KafkaPayloadReader",
    "KafkaRetentionGap",
    "KafkaSource",
    "MemoryCheckpointStore",
    "MemoryFailureStore",
    "MultiSourceWindowState",
    "NativeRayAdapter",
    "PayloadReader",
    "PluginManager",
    "PluginStore",
    "PostgresCursor",
    "PostgresPayloadReader",
    "PostgresSource",
    "RayAdapter",
    "RayDispatcher",
    "ReloadResult",
    "ResourceLoader",
    "ResourceRegistry",
    "ResourceSpec",
    "RunStatus",
    "SQLiteCheckpointStore",
    "SQLiteFailureStore",
    "SoftAction",
    "SourceDependencyError",
    "SourceIdle",
    "SourceKind",
    "SourceObserver",
    "SourceRegistry",
    "SourceSpec",
    "SourceState",
    "StaleBatchError",
    "TargetReached",
    "TriggerContext",
    "TriggerDecision",
    "TriggerPolicy",
    "ValidationResult",
    "WorkerDiscoveryError",
    "build_resource_registry",
    "build_eq_rule_labeler",
    "build_source_registry",
    "create_event_log",
    "create_plugin_router",
    "default_event_log",
    "discover_event_hooks",
    "discover_worker_roots",
    "discover_workers",
    "hook",
    "handler_shard_size",
    "merge_batch_windows",
    "merge_fetch_results",
    "normalize_batch_size",
    "resolve_resource",
    "resolve_source",
    "resource_from_mapping",
    "source_from_mapping",
    "validate_worker_py",
]
